version: '3.9'

services:
  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
      MONGO_INITDB_DATABASE: haasappprojectsdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask-app:
    build: .
    container_name: projects-microservice
    restart: always
    ports:
      - "2000:2000"
    env_file:
      - .env
    depends_on:
      - mongo-auth
    environment:
      - FLASK_ENV=production
      - PORT=2000

volumes:
  mongo-data:
