# For adding MongoDB to Docker Compose

services:
  # MongoDB Service
  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - auth-network

  # Flask User Auth Service
  user-auth:
    build: .
    container_name: user-auth-service
    depends_on:
      - mongo-auth
    environment:
      PORT: 5001
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_HOST: mongo-auth
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "5001:5001"
    networks:
      - auth-network


# Persist MongoDB data
volumes:
  auth-mongo-data:

# Internal network for services
networks:
  auth-network:
    driver: bridge

